<template>
	<div class="loading">
		<div class="loadingio-spinner-rolling-ua5efh2co5k">
			<div class="ldio-93f11videjh">
				<div></div>
			</div>
		</div>
	</div>
</template>

<script>
	export default {
		name: "LoadingIndicator",
	};
</script>

<style lang='scss' scoped>
	@keyframes ldio-93f11videjh {
		0% {
			transform: translate(-50%, -50%) rotate(0deg);
		}
		100% {
			transform: translate(-50%, -50%) rotate(360deg);
		}
	}
	.ldio-93f11videjh div {
		position: absolute;
		width: 54px;
		height: 54px;
		border: 6px solid #a954ee;
		border-top-color: transparent;
		border-radius: 50%;
	}
	.ldio-93f11videjh div {
		animation: ldio-93f11videjh 0.5714285714285714s linear infinite;
		top: 100px;
		left: 100px;
	}
	.loadingio-spinner-rolling-ua5efh2co5k {
		width: 200px;
		height: 200px;
		display: inline-block;
		overflow: hidden;
		background: none;
	}
	.ldio-93f11videjh {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio-93f11videjh div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
</style>